/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultFolioPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  portfolioFolder: "portfolio",
  outputFolder: "_site",
  githubRepo: "",
  githubToken: "",
  siteName: "My Portfolio",
  theme: "apple",
  navLinks: "Work: #work",
  heroTitle: "Pro. Beyond.",
  heroSubtitle: "Welcome to my digital portfolio.",
  aboutText: "I'm a designer and developer building scalable, beautiful web applications.",
  quoteText: '"The details are not the details. They make the design."'
};

// src/parser.ts
var Parser = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async getPublishedNotes() {
    var _a;
    const folder = this.settings.portfolioFolder.replace(/\/+$/, "");
    const markdownFiles = this.app.vault.getMarkdownFiles().filter(
      (f) => f.path === `${folder}/${f.name}` || f.path.startsWith(`${folder}/`)
    );
    const published = [];
    for (const file of markdownFiles) {
      const cache = this.app.metadataCache.getFileCache(file);
      const frontmatter = (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : {};
      if (frontmatter.published !== true)
        continue;
      const content = await this.app.vault.read(file);
      const title = typeof frontmatter.title === "string" && frontmatter.title.trim() ? frontmatter.title.trim() : file.basename;
      published.push({ path: file.path, title, frontmatter, content, imageRefs: extractImageRefs(content) });
    }
    return published;
  }
};
async function getPublishedNotes(app, portfolioFolder) {
  return new Parser(app, { portfolioFolder }).getPublishedNotes();
}
function parseNote(rawContent, fallbackSlug) {
  var _a, _b;
  const frontmatter = extractFrontmatter(rawContent);
  const body = stripFrontmatter(rawContent);
  const slug = (_b = frontmatter.slug) != null ? _b : slugify((_a = frontmatter.title) != null ? _a : fallbackSlug);
  return { frontmatter, body, slug };
}
function extractFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match)
    return {};
  const fm = parseYamlSimple(match[1]);
  if (Array.isArray(fm.tags)) {
    fm.tags = fm.tags.map((t) => String(t).toLowerCase());
  }
  return fm;
}
function stripFrontmatter(content) {
  return content.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, "").trim();
}
function parseYamlSimple(yaml) {
  const result = {};
  const lines = yaml.split(/\r?\n/);
  let currentKey = null;
  let inArray = false;
  for (const line of lines) {
    const arrayItem = line.match(/^\s+-\s+(.+)/);
    if (arrayItem && currentKey && inArray) {
      const arr = result[currentKey];
      if (Array.isArray(arr))
        arr.push(arrayItem[1].trim());
      continue;
    }
    const kvMatch = line.match(/^([a-zA-Z_][\w-]*):\s*(.*)/);
    if (kvMatch) {
      currentKey = kvMatch[1];
      const value = kvMatch[2].trim();
      if (value === "") {
        result[currentKey] = [];
        inArray = true;
      } else if (value.startsWith("[")) {
        result[currentKey] = value.replace(/^\[|\]$/g, "").split(",").map((s) => s.trim().replace(/^["']|["']$/g, ""));
        inArray = false;
      } else {
        result[currentKey] = value.replace(/^["']|["']$/g, "");
        inArray = false;
      }
    }
  }
  return result;
}
var IMAGE_EXT_RE = /\.(png|jpe?g|gif|webp|svg)$/i;
function extractImageRefs(content) {
  const refs = [];
  const seen = /* @__PURE__ */ new Set();
  const wikiRe = /!\[\[([^\]]+)\]\]/g;
  let m;
  while ((m = wikiRe.exec(content)) !== null) {
    const path = m[1].split("|")[0].trim();
    if (IMAGE_EXT_RE.test(path) && !seen.has(path)) {
      seen.add(path);
      refs.push({ type: "wikilink", path });
    }
  }
  const mdRe = /!\[[^\]]*\]\(([^)]+)\)/g;
  while ((m = mdRe.exec(content)) !== null) {
    const path = m[1].trim().replace(/\s+["'][^"']*["']\s*$/, "");
    if (!path.startsWith("http") && IMAGE_EXT_RE.test(path) && !seen.has(path)) {
      seen.add(path);
      refs.push({ type: "markdown", path });
    }
  }
  return refs;
}
function slugify(text) {
  return text.toLowerCase().trim().replace(/[^\w\s-]/g, "").replace(/\s+/g, "-");
}

// src/builder.ts
var CARD_COLORS = ["#1A1A2E", "#16213E", "#1B1B2F", "#0F3460", "#1C1C1E", "#2D1B69"];
var CALLOUT_ICONS = {
  note: "\u{1F4DD}",
  info: "\u2139\uFE0F",
  tip: "\u{1F4A1}",
  warning: "\u26A0\uFE0F",
  danger: "\u{1F534}",
  question: "\u2753",
  success: "\u2705",
  failure: "\u274C",
  bug: "\u{1F41B}",
  example: "\u{1F4CB}",
  quote: "\u{1F4AC}",
  abstract: "\u{1F4C4}"
};
var CALLOUT_CSS = `
.callout { border-radius: 6px; padding: 12px 16px; margin: 16px 0; border-left: 4px solid; }
.callout-title { display: flex; align-items: center; gap: 8px; font-weight: 600; margin-bottom: 8px; font-size: 14px; }
.callout-icon { font-size: 16px; line-height: 1; }
.callout-content { font-size: 14px; line-height: 1.6; }
.callout-note     { background: #f0f4ff; border-color: #3b82f6; color: #1e3a8a; }
.callout-info     { background: #f0f9ff; border-color: #0ea5e9; color: #0c4a6e; }
.callout-tip      { background: #f0fdf4; border-color: #22c55e; color: #14532d; }
.callout-warning  { background: #fffbeb; border-color: #f59e0b; color: #78350f; }
.callout-danger   { background: #fff1f2; border-color: #ef4444; color: #7f1d1d; }
.callout-question { background: #faf5ff; border-color: #a855f7; color: #4a1d96; }
.callout-success  { background: #f0fdf4; border-color: #22c55e; color: #14532d; }
.callout-failure  { background: #fff1f2; border-color: #ef4444; color: #7f1d1d; }
.callout-bug      { background: #fff1f2; border-color: #ef4444; color: #7f1d1d; }
.callout-example  { background: #f8fafc; border-color: #64748b; color: #1e293b; }
.callout-quote    { background: #f8fafc; border-color: #64748b; color: #1e293b; }
.callout-abstract { background: #f0f9ff; border-color: #0ea5e9; color: #0c4a6e; }
`.trim();
var BASE_CSS = `
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:ital,wght@0,300;0,400;0,500;1,400&display=swap');

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  background: #0A0A0A;
  color: #FFFFFF;
  font-family: 'DM Sans', sans-serif;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}
a { color: inherit; text-decoration: none; }
img { max-width: 100%; height: auto; display: block; }

/* \u2500\u2500 Navigation \u2500\u2500 */
.vf-nav {
  position: fixed; top: 0; left: 0; right: 0; z-index: 200;
  height: 64px;
  display: flex; align-items: center; justify-content: space-between;
  padding: 0 60px;
  background: transparent;
  backdrop-filter: blur(0px);
  -webkit-backdrop-filter: blur(0px);
  border-bottom: 1px solid transparent;
  transition: background 0.4s ease, backdrop-filter 0.4s ease, border-color 0.4s ease;
}
.vf-nav.scrolled {
  background: rgba(0,0,0,0.9);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  border-bottom-color: rgba(255,255,255,0.1);
}
.vf-nav-logo {
  font-family: 'Syne', sans-serif;
  font-size: 16px; font-weight: 700;
  letter-spacing: 0.05em; text-transform: uppercase;
  color: #FFFFFF;
}
.vf-nav-links { display: flex; gap: 36px; }
.vf-nav-link {
  font-size: 13px; font-weight: 400; letter-spacing: 0.04em;
  color: rgba(255,255,255,0.7);
  transition: color 0.2s ease;
}
.vf-nav-link:hover { color: #FFFFFF; }

/* \u2500\u2500 Hero \u2500\u2500 */
.vf-hero {
  height: 100vh;
  min-height: 600px;
  background: #0A0A0A;
  display: flex; align-items: center; justify-content: center;
  text-align: center;
  position: relative;
  overflow: hidden;
}
.vf-hero::before {
  content: '';
  position: absolute; inset: 0;
  background: radial-gradient(ellipse 80% 60% at 50% 40%, rgba(255,77,0,0.07) 0%, transparent 70%);
  pointer-events: none;
}
.vf-hero-inner { position: relative; z-index: 1; padding: 0 40px; max-width: 1100px; }
.vf-hero-label {
  display: block; margin-bottom: 32px;
  font-size: 11px; font-weight: 400;
  letter-spacing: 0.3em; text-transform: uppercase;
  color: rgba(255,255,255,0.4);
}
.vf-hero-title {
  font-family: 'Syne', sans-serif;
  font-size: clamp(60px, 12vw, 140px);
  font-weight: 800;
  letter-spacing: -4px;
  line-height: 0.9;
  color: #FFFFFF;
  margin-bottom: 32px;
}
.vf-hero-title em {
  font-style: italic;
  color: #FF4D00;
}
.vf-hero-subtitle {
  font-size: 16px; font-weight: 300;
  color: rgba(255,255,255,0.5);
  line-height: 1.7;
  max-width: 480px;
  margin: 0 auto 60px;
}
.vf-scroll-indicator {
  position: absolute; bottom: 48px; left: 50%; transform: translateX(-50%);
  display: flex; flex-direction: column; align-items: center; gap: 10px;
  color: rgba(255,255,255,0.3);
  font-size: 11px; letter-spacing: 0.2em; text-transform: uppercase;
}
.vf-scroll-line {
  width: 1px; height: 60px;
  background: linear-gradient(to bottom, rgba(255,255,255,0.3), transparent);
  animation: vf-scroll-pulse 2s ease-in-out infinite;
}
@keyframes vf-scroll-pulse {
  0%, 100% { opacity: 0.3; transform: scaleY(1); }
  50% { opacity: 0.8; transform: scaleY(0.6); }
}

/* \u2500\u2500 Projects strip section \u2500\u2500 */
.vf-projects-section {
  background: #0A0A0A;
  padding: 120px 60px;
  max-width: 1400px;
  margin: 0 auto;
}
.vf-section-label {
  display: block; margin-bottom: 60px;
  font-size: 11px; font-weight: 400;
  letter-spacing: 0.3em; text-transform: uppercase;
  color: rgba(255,255,255,0.3);
}

/* \u2500\u2500 Project row \u2500\u2500 */
.vf-project-row {
  display: grid;
  grid-template-columns: 60px 1fr auto;
  align-items: center;
  gap: 40px;
  padding: 40px 0;
  border-top: 1px solid rgba(255,255,255,0.1);
  text-decoration: none; color: #FFFFFF;
  transition: background 0.3s ease;
  cursor: pointer;
  border-radius: 4px;
  margin: 0 -20px;
  padding-left: 20px;
  padding-right: 20px;
}
.vf-project-row:hover { background: rgba(255,255,255,0.03); }
.vf-project-row:last-child { border-bottom: 1px solid rgba(255,255,255,0.1); }
.vf-project-num {
  font-family: 'Syne', sans-serif;
  font-size: 12px; font-weight: 400;
  color: rgba(255,255,255,0.2);
  letter-spacing: 0.1em;
}
.vf-project-name {
  font-family: 'Syne', sans-serif;
  font-size: clamp(28px, 4vw, 56px);
  font-weight: 700;
  letter-spacing: -1.5px;
  line-height: 1;
  color: #FFFFFF;
  transition: color 0.3s ease;
}
.vf-project-row:hover .vf-project-name { color: #FF4D00; }
.vf-project-meta-right {
  display: flex; flex-direction: column; align-items: flex-end; gap: 10px;
  flex-shrink: 0;
}
.vf-project-year {
  font-size: 12px; color: rgba(255,255,255,0.3);
  letter-spacing: 0.08em;
}
.vf-project-tags-row { display: flex; flex-wrap: wrap; gap: 6px; justify-content: flex-end; }
.vf-project-tag-pill {
  font-size: 11px; font-weight: 400;
  color: rgba(255,255,255,0.6);
  padding: 4px 12px;
  border: 1px solid rgba(255,255,255,0.15);
  border-radius: 100px;
  white-space: nowrap;
}
.vf-no-projects {
  font-size: 16px; color: rgba(255,255,255,0.3);
  padding: 60px 0;
}

/* \u2500\u2500 Filters \u2500\u2500 */
.vf-filter-bar { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 16px; margin-bottom: 32px; }
.vf-filter-btn {
  background: transparent; border: 1px solid rgba(255,255,255,0.15); color: rgba(255,255,255,0.6);
  padding: 6px 16px; border-radius: 100px; font-size: 13px; cursor: pointer; transition: all 0.2s; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
}
.vf-filter-btn:hover { border-color: rgba(255,255,255,0.4); color: #fff; }
.vf-filter-btn.active { background: #fff; color: #000; border-color: #fff; font-weight: 500; }

/* \u2500\u2500 About \u2500\u2500 */
.vf-about { background: #111111; padding: 120px 60px; }
.vf-about-inner {
  max-width: 1400px; margin: 0 auto;
  display: grid; grid-template-columns: 1fr 1fr; gap: 80px; align-items: start;
}
.vf-about-left {}
.vf-about-heading {
  font-family: 'Syne', sans-serif;
  font-size: clamp(36px, 4vw, 52px);
  font-weight: 700;
  color: #FFFFFF;
  line-height: 1.1;
  letter-spacing: -1.5px;
  margin-bottom: 24px;
}
.vf-about-body {
  font-size: 16px; font-weight: 300;
  color: rgba(255,255,255,0.5);
  line-height: 1.8;
  max-width: 480px;
}
.vf-about-right {}
.vf-about-detail {
  display: flex; flex-direction: column; gap: 28px;
  padding-top: 8px;
}
.vf-about-detail-item {}
.vf-about-detail-label {
  font-size: 10px; font-weight: 500; letter-spacing: 0.25em; text-transform: uppercase;
  color: rgba(255,255,255,0.25);
  margin-bottom: 8px;
}
.vf-about-detail-value {
  font-size: 15px; color: rgba(255,255,255,0.7);
  font-weight: 300;
}
.vf-skills { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 4px; }
.vf-skill {
  font-size: 12px; color: rgba(255,255,255,0.5);
  padding: 6px 14px;
  border: 1px solid rgba(255,255,255,0.12);
  border-radius: 100px;
  font-weight: 400;
  transition: border-color 0.2s, color 0.2s;
}
.vf-skill:hover { border-color: rgba(255,77,0,0.5); color: #FF4D00; }

/* \u2500\u2500 Footer \u2500\u2500 */
.vf-footer {
  background: #0A0A0A;
  border-top: 1px solid rgba(255,255,255,0.1);
  padding: 48px 60px;
  display: flex; align-items: center; justify-content: space-between;
}
.vf-footer-left {
  font-family: 'Syne', sans-serif;
  font-size: 14px; font-weight: 700; letter-spacing: 0.05em; text-transform: uppercase;
  color: #FFFFFF;
}
.vf-footer-right {
  font-size: 12px; color: rgba(255,255,255,0.3);
}
.vf-footer-right a { color: #FF4D00; transition: opacity 0.2s; }
.vf-footer-right a:hover { opacity: 0.7; }

/* \u2500\u2500 Back button \u2500\u2500 */
.vf-back-wrap {
  position: absolute; top: 80px; left: 60px; z-index: 10;
}
.vf-back-btn {
  display: inline-flex; align-items: center; gap: 8px;
  font-size: 13px; font-weight: 400; letter-spacing: 0.04em;
  color: rgba(255,255,255,0.7);
  transition: color 0.2s ease;
}
.vf-back-btn::before {
  content: '\u2190';
  font-size: 16px;
}
.vf-back-btn:hover { color: #FFFFFF; }

/* \u2500\u2500 Project page \u2500\u2500 */
.vf-project-page { background: #0A0A0A; min-height: 100vh; position: relative; }

.vf-project-hero-block {
  width: 100%;
  height: 50vh; min-height: 400px;
  display: flex; align-items: center; justify-content: center;
  position: relative;
  overflow: hidden;
}
.vf-project-hero-block::after {
  content: '';
  position: absolute; inset: 0;
  background: rgba(0,0,0,0.35);
}
.vf-project-hero-title {
  position: relative; z-index: 1;
  font-family: 'Syne', sans-serif;
  font-size: clamp(36px, 5vw, 72px);
  font-weight: 800;
  letter-spacing: -2px;
  line-height: 1;
  color: #FFFFFF;
  text-align: center;
  padding: 0 40px;
}

.vf-project-content {
  max-width: 720px; margin: 0 auto;
  padding: 80px 40px 120px;
}
.vf-project-content-title {
  font-family: 'Syne', sans-serif;
  font-size: clamp(28px, 3vw, 42px);
  font-weight: 700;
  letter-spacing: -1px;
  color: #FFFFFF;
  margin-bottom: 12px;
}
.vf-project-date-line {
  font-size: 13px; color: rgba(255,255,255,0.3);
  letter-spacing: 0.08em;
  margin-bottom: 20px;
}
.vf-project-tags-line { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 48px; }
.vf-project-page-tag {
  font-size: 12px; font-weight: 500;
  color: #FF4D00;
  background: rgba(255,77,0,0.1);
  border: 1px solid rgba(255,77,0,0.3);
  padding: 5px 14px; border-radius: 100px;
}

/* \u2500\u2500 Prose \u2500\u2500 */
.vf-prose { }
.vf-prose h1 {
  font-family: 'Syne', sans-serif;
  font-size: 32px; font-weight: 700; letter-spacing: -0.5px; line-height: 1.2;
  color: #FFFFFF; margin: 2.5rem 0 1rem;
}
.vf-prose h2 {
  font-family: 'Syne', sans-serif;
  font-size: 26px; font-weight: 700; letter-spacing: -0.3px; line-height: 1.2;
  color: #FFFFFF; margin: 2.5rem 0 1rem;
}
.vf-prose h3 {
  font-family: 'Syne', sans-serif;
  font-size: 20px; font-weight: 600; line-height: 1.3;
  color: #FFFFFF; margin: 2rem 0 0.8rem;
}
.vf-prose h4, .vf-prose h5, .vf-prose h6 {
  font-size: 17px; font-weight: 600;
  color: #FFFFFF; margin: 1.5rem 0 0.6rem;
}
.vf-prose p {
  font-size: 18px; line-height: 1.9; font-weight: 300;
  color: rgba(255,255,255,0.75); margin: 1.4rem 0;
}
.vf-prose a { color: #FF4D00; }
.vf-prose a:hover { text-decoration: underline; }
.vf-prose strong { font-weight: 600; color: #FFFFFF; }
.vf-prose em { font-style: italic; color: rgba(255,255,255,0.9); }
.vf-prose ul { list-style: disc; padding-left: 1.5rem; margin: 1rem 0; }
.vf-prose ol { list-style: decimal; padding-left: 1.5rem; margin: 1rem 0; }
.vf-prose li { font-size: 18px; line-height: 1.9; font-weight: 300; color: rgba(255,255,255,0.75); margin: 0.4rem 0; }
.vf-prose code {
  background: rgba(255,255,255,0.07); color: rgba(255,255,255,0.9);
  padding: 2px 7px; border-radius: 4px;
  font-size: 0.875em; font-family: 'SF Mono', SFMono-Regular, Consolas, 'Liberation Mono', monospace;
}
.vf-prose pre {
  background: #111111; color: rgba(255,255,255,0.85);
  padding: 28px; border-radius: 8px; overflow-x: auto;
  margin: 2rem 0; border: 1px solid rgba(255,255,255,0.08);
}
.vf-prose pre code { background: none; padding: 0; color: inherit; }
.vf-prose blockquote {
  border-left: 2px solid #FF4D00;
  padding: 4px 0 4px 24px;
  color: rgba(255,255,255,0.45);
  font-style: italic; margin: 1.5rem 0;
}
.vf-prose hr { border: none; border-top: 1px solid rgba(255,255,255,0.1); margin: 3rem 0; }
.vf-prose img { border-radius: 8px; margin: 0; }
.vf-gallery { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin: 3rem 0; }
.vf-gallery.cols-4 { grid-template-columns: repeat(4, 1fr); }
.vf-gallery img { margin: 0; width: 100%; height: 100%; object-fit: cover; border-radius: 8px; }
.vf-image-single { display: flex; justify-content: center; margin: 3rem 0; }

/* \u2500\u2500 Nav scroll JS \u2500\u2500 */
/* (handled inline via script) */

/* \u2500\u2500 Responsive \u2500\u2500 */
@media (max-width: 768px) {
  .vf-nav { padding: 0 24px; }
  .vf-nav-links { display: none; }

  .vf-hero-title { letter-spacing: -2px; }
  .vf-hero-subtitle { font-size: 15px; }

  .vf-projects-section { padding: 80px 24px; }
  .vf-project-row {
    grid-template-columns: 40px 1fr;
    gap: 16px;
    margin: 0 -12px;
    padding-left: 12px;
    padding-right: 12px;
  }
  .vf-project-meta-right { display: none; }
  .vf-project-name { font-size: clamp(22px, 6vw, 36px); letter-spacing: -1px; }

  .vf-about { padding: 80px 24px; }
  .vf-about-inner { grid-template-columns: 1fr; gap: 48px; }
  .vf-about-heading { font-size: 32px; }

  .vf-footer { flex-direction: column; gap: 12px; text-align: center; padding: 40px 24px; }

  .vf-back-wrap { left: 24px; top: 72px; }

  .vf-project-content { padding: 60px 24px 80px; }
  .vf-prose p, .vf-prose li { font-size: 16px; }
}
${CALLOUT_CSS}
`.trim();
function htmlHead(pageTitle) {
  return `  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${pageTitle}</title>
  <style>${BASE_CSS}</style>`;
}
function normalizeNavHref(href) {
  if (!href)
    return href;
  if (href.startsWith("#") || href.startsWith("/") || href.startsWith("./") || href.startsWith("../"))
    return href;
  if (/^https?:\/\//.test(href) || /^mailto:/.test(href))
    return href;
  return "https://" + href;
}
function renderNav(siteName, root = "", navLinks = "Work: #work, About: #about") {
  const linkItems = navLinks.split(",").map((entry) => {
    const parts = entry.trim().split(":");
    const label = parts[0].trim();
    const rawHref = parts.slice(1).join(":").trim();
    if (!label || !rawHref)
      return "";
    const fullHref = normalizeNavHref(rawHref);
    const isExternal = /^https?:\/\//.test(fullHref);
    const targetAttr = isExternal ? ` target="_blank" rel="noopener noreferrer"` : "";
    return `<a href="${escapeHtml(fullHref)}" class="vf-nav-link"${targetAttr}>${escapeHtml(label)}</a>`;
  }).filter(Boolean).join("\n    ");
  return `<nav class="vf-nav" id="vf-nav">
  <a href="${root}index.html" class="vf-nav-logo">${escapeHtml(siteName)}</a>
  <div class="vf-nav-links">
    ${linkItems}
  </div>
</nav>
<script>
(function(){
  var nav = document.getElementById('vf-nav');
  window.addEventListener('scroll', function(){
    if(window.scrollY > 40){ nav.classList.add('scrolled'); }
    else { nav.classList.remove('scrolled'); }
  }, { passive: true });
})();
<\/script>`;
}
function renderFooter(siteName) {
  return `<footer class="vf-footer">
  <span class="vf-footer-left">${escapeHtml(siteName)}</span>
  <span class="vf-footer-right">Built with <a href="#">VaultFolio</a></span>
</footer>`;
}
function renderTagFilterScript() {
  return `<script>
document.addEventListener("DOMContentLoaded", () => {
  const filters = document.querySelectorAll(".vf-filter-btn");
  const cards = document.querySelectorAll(".vf-filter-card");
  
  filters.forEach(btn => {
    btn.addEventListener("click", () => {
      filters.forEach(f => f.classList.remove("active"));
      btn.classList.add("active");
      
      const tag = btn.getAttribute("data-filter");
      
      cards.forEach(card => {
        if (tag === "all") {
          card.style.display = "";
        } else {
          const cardTags = card.getAttribute("data-tags") || "";
          const tList = cardTags.split(" ");
          if (tList.includes(tag)) {
            card.style.display = "";
          } else {
            card.style.display = "none";
          }
        }
      });
    });
  });
});
<\/script>`;
}
function buildSite(notes, settings) {
  var _a;
  const siteTitle = settings.siteName;
  const theme = (_a = settings.theme) != null ? _a : "apple";
  let pages, index;
  if (theme === "editorial") {
    pages = notes.map((note) => buildEditorialPage(note, siteTitle));
    index = buildEditorialIndex(notes, settings);
  } else if (theme === "apple") {
    pages = notes.map((note) => buildApplePage(note, siteTitle));
    index = buildAppleIndex(notes, settings);
  } else if (theme === "swiss") {
    pages = notes.map((note) => buildSwissPage(note, siteTitle));
    index = buildSwissIndex(notes, settings);
  } else if (theme === "simple") {
    pages = notes.map((note) => buildSimplePage(note, siteTitle));
    index = buildSimpleIndex(notes, settings);
  } else {
    pages = notes.map((note) => buildPage(note, siteTitle));
    index = buildIndex(notes, settings);
  }
  return { files: [index, ...pages], pageCount: pages.length, imageMap: /* @__PURE__ */ new Map() };
}
function buildIndex(notes, settings) {
  const siteTitle = settings.siteName;
  const rows = notes.map((n, i) => {
    var _a;
    const num = String(i + 1).padStart(2, "0");
    const title = (_a = n.frontmatter.title) != null ? _a : n.slug;
    const tags = Array.isArray(n.frontmatter.tags) ? n.frontmatter.tags : [];
    const year = extractYear(n.frontmatter.date);
    const tagPills = tags.slice(0, 3).map((t) => `<span class="vf-project-tag-pill">${escapeHtml(t)}</span>`).join("");
    return `<a href="pages/${n.slug}.html" class="vf-project-row vf-filter-card" data-tags="${escapeHtml(tags.join(" "))}">
  <span class="vf-project-num">${num}</span>
  <span class="vf-project-name">${escapeHtml(title)}</span>
  <div class="vf-project-meta-right">
    ${year ? `<span class="vf-project-year">${escapeHtml(year)}</span>` : ""}
    ${tags.length > 0 ? `<div class="vf-project-tags-row">${tagPills}</div>` : ""}
  </div>
</a>`;
  }).join("\n");
  const allTags = collectTags(notes);
  const defaultSkills = ["Design", "Development", "Strategy", "UX", "React", "TypeScript"];
  const skills = allTags.length > 0 ? allTags : defaultSkills;
  const skillChips = skills.map((s) => `<span class="vf-skill">${escapeHtml(s)}</span>`).join("");
  const allTagsSorted = Array.from(allTags).sort();
  const filterHtml = allTagsSorted.length > 0 ? `
    <div class="vf-filter-bar">
      <button class="vf-filter-btn active" data-filter="all">All</button>
      ${allTagsSorted.map((t) => `<button class="vf-filter-btn" data-filter="${escapeHtml(t)}">${escapeHtml(t)}</button>`).join("")}
    </div>
  ` : "";
  const titleWords = escapeHtml(siteTitle).split(" ");
  const heroTitle = titleWords.length > 1 ? titleWords.slice(0, -1).join(" ") + " <em>" + titleWords[titleWords.length - 1] + "</em>" : "<em>" + titleWords[0] + "</em>";
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
${htmlHead(escapeHtml(siteTitle))}
</head>
<body>

${renderNav(siteTitle, "", settings.navLinks)}

<!-- Hero -->
<section class="vf-hero">
  <div class="vf-hero-inner">
    <span class="vf-hero-label">Portfolio &mdash; 2026</span>
    <h1 class="vf-hero-title">${heroTitle}</h1>
    <p class="vf-hero-subtitle">${escapeHtml(settings.heroSubtitle)}</p>
  </div>
  <div class="vf-scroll-indicator">
    <span>Scroll</span>
    <div class="vf-scroll-line"></div>
  </div>
</section>

<!-- Projects -->
<section id="work">
  <div class="vf-projects-section">
    <span class="vf-section-label">Selected Work</span>
    ${filterHtml}
    ${notes.length > 0 ? rows : `<p class="vf-no-projects">No published projects yet.</p>`}
  </div>
</section>

<!-- About -->
<section class="vf-about" id="about">
  <div class="vf-about-inner">
    <div class="vf-about-left">
      <h2 class="vf-about-heading">Building things that matter.</h2>
      <p class="vf-about-body">${settings.aboutText}</p>
    </div>
    <div class="vf-about-right">
      <div class="vf-about-detail">
        <div class="vf-about-detail-item">
          <div class="vf-about-detail-label">Skills</div>
          <div class="vf-skills">${skillChips}</div>
        </div>
        <div class="vf-about-detail-item">
          <div class="vf-about-detail-label">Available</div>
          <div class="vf-about-detail-value">Open to new opportunities</div>
        </div>
        <div class="vf-about-detail-item">
          <div class="vf-about-detail-label">Contact</div>
          <div class="vf-about-detail-value"><a href="mailto:" style="color:#FF4D00">Get in touch &rarr;</a></div>
        </div>
      </div>
    </div>
  </div>
</section>

${renderFooter(siteTitle)}

</body>
</html>`;
  return { path: "index.html", content: html };
}
function buildPage(note, siteTitle) {
  var _a, _b;
  const title = (_a = note.frontmatter.title) != null ? _a : note.slug;
  const description = (_b = note.frontmatter.description) != null ? _b : "";
  const date = note.frontmatter.date;
  const tags = Array.isArray(note.frontmatter.tags) ? note.frontmatter.tags : [];
  const idx = Math.abs(hashString(note.slug)) % CARD_COLORS.length;
  const heroBg = CARD_COLORS[idx];
  const tagChips = tags.map((t) => `<span class="vf-project-page-tag">${escapeHtml(String(t))}</span>`).join("");
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
${htmlHead(`${escapeHtml(title)} \u2014 ${escapeHtml(siteTitle)}`)}
  <meta name="description" content="${escapeHtml(description)}" />
</head>
<body class="vf-project-page">

${renderNav(siteTitle, "../")}

<div class="vf-back-wrap">
  <a href="../index.html" class="vf-back-btn">Back</a>
</div>

<div class="vf-project-hero-block" style="background:${heroBg}">
  <h1 class="vf-project-hero-title">${escapeHtml(title)}</h1>
</div>

<div class="vf-project-content">
  <h2 class="vf-project-content-title">${escapeHtml(title)}</h2>
  ${date ? `<p class="vf-project-date-line">${escapeHtml(String(date))}</p>` : ""}
  ${tags.length > 0 ? `<div class="vf-project-tags-line">${tagChips}</div>` : ""}
  <div class="vf-prose">
    ${markdownToHtml(note.body)}
  </div>
</div>

${renderFooter(siteTitle)}

</body>
</html>`;
  return { path: `pages/${note.slug}.html`, content: html };
}
function markdownToHtml(md) {
  let html = parseCallouts(md).replace(/^#{6}\s+(.+)$/gm, "<h6>$1</h6>").replace(/^#{5}\s+(.+)$/gm, "<h5>$1</h5>").replace(/^#{4}\s+(.+)$/gm, "<h4>$1</h4>").replace(/^#{3}\s+(.+)$/gm, "<h3>$1</h3>").replace(/^#{2}\s+(.+)$/gm, "<h2>$1</h2>").replace(/^#{1}\s+(.+)$/gm, "<h1>$1</h1>").replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>").replace(/\*(.+?)\*/g, "<em>$1</em>").replace(/`([^`\n]+)`/g, "<code>$1</code>").replace(/!\[\[([^\]]+)\]\]/g, (_, ref) => {
    var _a;
    const name = (_a = ref.split("|")[0].trim().split("/").pop()) != null ? _a : ref;
    return `<img src="../images/${encodeURIComponent(name)}" alt="${escapeHtml(name)}" />`;
  }).replace(/!\[([^\]]*)\]\(([^)]+)\)/g, (_, alt, rawSrc) => {
    var _a;
    const src = rawSrc.trim().replace(/\s+["'][^"']*["']\s*$/, "");
    if (/^https?:\/\//.test(src)) {
      return `<img src="${src}" alt="${escapeHtml(alt)}" />`;
    }
    const name = (_a = src.split("/").pop()) != null ? _a : src;
    return `<img src="../images/${encodeURIComponent(name)}" alt="${escapeHtml(alt)}" />`;
  }).replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2">$1</a>').replace(/^---$/gm, "<hr>").replace(/\n{2,}/g, "</p><p>").replace(/^(?!<[h1-6polbui])(.+)$/gm, "<p>$1</p>").trim();
  html = html.replace(/((?:<img[^>]+>\s*)+)/g, (match) => {
    const count = (match.match(/<img/g) || []).length;
    if (count > 1) {
      const colClass = count % 4 === 0 ? "cols-4" : "cols-2";
      return `<div class="vf-gallery ${colClass}">
${match.trim()}
</div>
`;
    } else if (count === 1) {
      return `<div class="vf-image-single">
${match.trim()}
</div>
`;
    }
    return match;
  });
  return html;
}
function collectTags(notes) {
  const seen = /* @__PURE__ */ new Set();
  for (const n of notes) {
    const t = n.frontmatter.tags;
    if (Array.isArray(t))
      t.forEach((tag) => seen.add(String(tag)));
  }
  return [...seen];
}
function extractYear(date) {
  if (!date)
    return "";
  const m = date.match(/\d{4}/);
  return m ? m[0] : "";
}
function hashString(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++)
    h = Math.imul(31, h) + s.charCodeAt(i) | 0;
  return h;
}
function escapeHtml(str) {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function applyInlineMd(text) {
  return text.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>").replace(/\*(.+?)\*/g, "<em>$1</em>").replace(/`([^`\n]+)`/g, "<code>$1</code>").replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2">$1</a>');
}
function parseCallouts(md) {
  var _a;
  const lines = md.split("\n");
  const out = [];
  let i = 0;
  while (i < lines.length) {
    const match = lines[i].match(/^>\s*\[!([\w]+)\]\s*(.*)/);
    if (match) {
      const type = match[1].toLowerCase();
      const title = match[2].trim() || type.charAt(0).toUpperCase() + type.slice(1);
      const contentLines = [];
      i++;
      while (i < lines.length && /^>\s?/.test(lines[i])) {
        contentLines.push(lines[i].replace(/^>\s?/, ""));
        i++;
      }
      const icon = (_a = CALLOUT_ICONS[type]) != null ? _a : "\u{1F4DD}";
      const contentHtml = contentLines.map(applyInlineMd).join("<br>");
      out.push(
        `<div class="callout callout-${escapeHtml(type)}"><div class="callout-title"><span class="callout-icon">${icon}</span><span class="callout-title-text">${escapeHtml(title)}</span></div><div class="callout-content">${contentHtml}</div></div>`
      );
    } else {
      out.push(lines[i]);
      i++;
    }
  }
  return out.join("\n");
}
var EDITORIAL_CSS = `
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&display=swap');

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body.vf-editorial {
  background: #FFFFFF;
  color: #0A0A0A;
  font-family: 'DM Sans', sans-serif;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}
.vf-editorial a { color: inherit; text-decoration: none; }
.vf-editorial img { max-width: 100%; height: auto; display: block; margin: 0; }
.vf-gallery { display: grid; grid-template-columns: repeat(2, 1fr); gap: 2px; margin: 40px 0; }
.vf-gallery.cols-4 { grid-template-columns: repeat(4, 1fr); }
.vf-gallery img { margin: 0; aspect-ratio: 3/4; object-fit: cover; border-radius: 0; }
.vf-image-single { display: flex; justify-content: center; margin: 40px 0; }

/* Navigation */
.vf-nav-ed {
  background: #FFFFFF;
  border-top: 4px solid #0A0A0A;
  border-bottom: 1px solid #0A0A0A;
  padding: 16px 40px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.vf-nav-ed-logo {
  font-family: 'Playfair Display', serif;
  font-size: 24px;
  font-weight: 700;
  color: #0A0A0A;
}
.vf-nav-ed-left, .vf-nav-ed-right {
  font-size: 14px;
  font-variant: small-caps;
}

/* Hero */
.vf-hero-ed {
  background: #FFFFFF;
  padding: 80px 40px 40px;
}
.vf-hero-ed-title {
  font-family: 'Playfair Display', serif;
  font-size: clamp(48px, 10vw, 120px);
  font-weight: 900;
  letter-spacing: -3px;
  line-height: 0.9;
  color: #0A0A0A;
  text-align: left;
}
.vf-hero-ed-divider {
  border-bottom: 3px solid #0A0A0A;
  margin: 40px 0;
}
.vf-hero-ed-cols {
  display: flex; gap: 40px;
  justify-content: space-between;
}
.vf-hero-ed-bio {
  font-family: 'Playfair Display', serif;
  font-style: italic;
  font-size: 24px;
  max-width: 600px;
}
.vf-hero-ed-stats {
  display: flex; gap: 40px;
}
.vf-hero-ed-stat {
  display: flex; flex-direction: column;
}
.vf-hero-ed-stat-val {
  font-family: 'Playfair Display', serif;
  font-size: 32px; font-weight: 700;
}
.vf-hero-ed-stat-lbl {
  font-size: 12px; text-transform: uppercase; letter-spacing: 0.1em;
}

/* Projects */
.vf-filter-bar { display: flex; flex-wrap: wrap; gap: 8px; justify-content: center; margin-bottom: 24px; }
.vf-filter-btn { background: transparent; border: 1px solid #0A0A0A; padding: 4px 16px; border-radius: 4px; font-family: 'DM Sans', sans-serif; font-size: 13px; font-weight: 700; cursor: pointer; text-transform: uppercase; letter-spacing: 0.05em; transition: all 0.2s; }
.vf-filter-btn:hover { background: rgba(0,0,0,0.05); }
.vf-filter-btn.active { background: #0A0A0A; color: #FFFFFF; }

.vf-projects-ed {
  padding: 80px 40px;
  max-width: 1200px;
  margin: 0 auto;
}
.vf-projects-ed-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1px;
  background: #0A0A0A;
  border: 1px solid #0A0A0A;
}
.vf-card-ed {
  background: #FFFFFF;
  display: flex; flex-direction: column;
  position: relative;
  text-decoration: none;
  color: #0A0A0A;
}
.vf-card-ed.full { grid-column: 1 / -1; }
.vf-card-ed-header {
  padding: 40px;
  min-height: 300px;
  display: flex; flex-direction: column;
  border-radius: 0;
}
.vf-card-ed-num {
  font-size: 14px;
  margin-bottom: auto;
}
.vf-card-ed-title {
  font-family: 'Playfair Display', serif;
  font-weight: 700;
  font-size: 32px;
  margin-bottom: 16px;
}
.vf-card-ed-desc {
  font-family: 'DM Sans', sans-serif;
  font-size: 14px;
  margin-bottom: 24px;
}
.vf-card-ed-tags {
  text-transform: uppercase;
  letter-spacing: 0.1em;
  font-size: 12px;
  margin-bottom: 24px;
}
.vf-card-ed-link {
  font-weight: 700;
  font-family: 'DM Sans', sans-serif;
  font-size: 14px;
  padding-bottom: 2px;
  align-self: flex-start;
}

/* Quote */
.vf-quote-ed {
  background: #0A0A0A;
  padding: 80px 40px;
  text-align: center;
}
.vf-quote-ed-text {
  font-family: 'Playfair Display', serif;
  font-size: clamp(28px, 4vw, 56px);
  font-style: italic;
  color: #FFFFFF;
}

/* Footer */
.vf-footer-ed {
  border-top: 4px solid #0A0A0A;
  background: #FFFFFF;
  padding: 80px 40px 40px;
}
.vf-footer-ed-cols {
  display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 40px;
  margin-bottom: 80px;
  font-family: 'Playfair Display', serif;
  font-size: 14px; color: #555;
  max-width: 1200px; margin: 0 auto;
}
.vf-footer-ed-bottom {
  text-align: center; font-size: 11px; color: #999;
  font-family: 'DM Sans', sans-serif;
}

/* Project Page */
.vf-page-ed-header {
  text-align: center;
  padding: 80px 40px 40px;
  border-bottom: 1px solid #0A0A0A;
  max-width: 1200px; margin: 0 auto;
}
.vf-page-ed-issue {
  font-variant: small-caps; margin-bottom: 24px; color: #555;
}
.vf-page-ed-title {
  font-family: 'Playfair Display', serif; font-size: 72px; font-weight: 900; line-height: 1.1; margin-bottom: 24px;
}
.vf-page-ed-meta { font-size: 18px; font-family: 'DM Sans', sans-serif; }

.vf-page-ed-content {
  max-width: 680px; margin: 0 auto; padding: 80px 40px;
}
.vf-prose-ed p {
  font-size: 18px; line-height: 1.9; margin: 1.5rem 0;
}
.vf-prose-ed p:first-of-type::first-letter {
  float: left; font-family: 'Playfair Display', serif; font-size: 72px; line-height: 60px;
  padding-right: 8px; font-weight: 900;
}
.vf-prose-ed a {
  color: #0A0A0A; text-decoration: underline;
}
.vf-prose-ed strong {
  font-weight: 700;
}
.vf-prose-ed pre, .vf-prose-ed code {
  background: #F5F4EF;
  color: #0A0A0A;
  border-radius: 4px;
}
.vf-prose-ed pre { padding: 16px; overflow-x: auto; font-size: 14px; }
.vf-prose-ed code { padding: 2px 4px; }

.vf-page-ed-tags { display: flex; gap: 8px; margin-top: 60px; }
.vf-page-ed-tag { font-variant: small-caps; border: 1px solid #0A0A0A; padding: 4px 12px; font-size: 12px; }

.vf-page-ed-back {
  position: absolute; top: 40px; left: 40px; font-size: 14px; color: #555; text-decoration: none;
}
.vf-page-ed-back:hover { color: #0A0A0A; }

@media (max-width: 768px) {
  .vf-hero-ed-cols { flex-direction: column; }
  .vf-projects-ed-grid { grid-template-columns: 1fr; }
  .vf-footer-ed-cols { grid-template-columns: 1fr; }
  .vf-page-ed-title { font-size: 48px; }
  .vf-nav-ed-left, .vf-nav-ed-right { display: none; }
}
${CALLOUT_CSS}
`;
var ED_COLORS = ["#F5F4EF", "#E8E4DC", "#1A1A1A", "#F0EBE0"];
function buildEditorialIndex(notes, settings) {
  const siteTitle = settings.siteName;
  const rows = notes.map((n, i) => {
    var _a, _b;
    const num = String(i + 1).padStart(2, "0");
    const title = (_a = n.frontmatter.title) != null ? _a : n.slug;
    const desc = (_b = n.frontmatter.description) != null ? _b : "";
    const tags = Array.isArray(n.frontmatter.tags) ? n.frontmatter.tags : [];
    const isFull = i % 3 === 0;
    const fullClass = isFull ? " full" : "";
    const bgColor = ED_COLORS[i % ED_COLORS.length];
    const textColor = bgColor === "#1A1A1A" ? "#FFFFFF" : "#0A0A0A";
    const tagsStr = tags.slice(0, 3).join(" \u2022 ");
    return `
<a href="pages/${n.slug}.html" class="vf-card-ed${fullClass} vf-filter-card" data-tags="${escapeHtml(tags.join(" "))}">
  <div class="vf-card-ed-header" style="background: ${bgColor}; color: ${textColor};">
    <div class="vf-card-ed-num">NO. ${num}</div>
    <div class="vf-card-ed-title">${escapeHtml(title)}</div>
    ${desc ? `<div class="vf-card-ed-desc">${escapeHtml(desc)}</div>` : ""}
    ${tagsStr ? `<div class="vf-card-ed-tags">${escapeHtml(tagsStr)}</div>` : ""}
    <div class="vf-card-ed-link" style="border-bottom-color: ${textColor}">Read more &rarr;</div>
  </div>
</a>`;
  }).join("n");
  const allTags = Array.from(new Set(notes.flatMap((n) => Array.isArray(n.frontmatter.tags) ? n.frontmatter.tags : []))).sort();
  const filterHtml = allTags.length > 0 ? `
    <div class="vf-filter-bar">
      <button class="vf-filter-btn active" data-filter="all">All</button>
      ${allTags.map((t) => `<button class="vf-filter-btn" data-filter="${escapeHtml(t)}">${escapeHtml(t)}</button>`).join("")}
    </div>
  ` : "";
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(siteTitle)} \u2014 Editorial</title>
  <style>${EDITORIAL_CSS}</style>
</head>
<body class="vf-editorial">

<nav class="vf-nav-ed">
  <div class="vf-nav-ed-left">April 2026</div>
  <div class="vf-nav-ed-logo">${escapeHtml(siteTitle)}</div>
  <div class="vf-nav-ed-right">Vol. 1</div>
</nav>

<section class="vf-hero-ed">
  <h1 class="vf-hero-ed-title">${escapeHtml(siteTitle)}</h1>
  <div class="vf-hero-ed-divider"></div>
  <div class="vf-hero-ed-cols">
    <div class="vf-hero-ed-bio">${escapeHtml(settings.heroSubtitle)}</div>
    <div class="vf-hero-ed-stats">
      <div class="vf-hero-ed-stat">
        <span class="vf-hero-ed-stat-val">${notes.length}</span>
        <span class="vf-hero-ed-stat-lbl">Projects</span>
      </div>
      <div class="vf-hero-ed-stat">
        <span class="vf-hero-ed-stat-val">10+</span>
        <span class="vf-hero-ed-stat-lbl">Years</span>
      </div>
    </div>
  </div>
</section>

<section class="vf-projects-ed">
  ${filterHtml}
  <div class="vf-projects-ed-grid">
    ${rows}
  </div>
</section>

<section class="vf-quote-ed">
  <p class="vf-quote-ed-text">${escapeHtml(settings.quoteText)}</p>
</section>

<footer class="vf-footer-ed">
  <div class="vf-footer-ed-cols">
    <div><strong>About</strong><br>Crafting digital experiences with precision, intention, and a relentless eye for detail.</div>
    <div><strong>Links</strong><br>Instagram<br>Twitter<br>LinkedIn</div>
    <div><strong>Contact</strong><br>hello@example.com</div>
  </div>
  <div class="vf-footer-ed-bottom">Published with VaultFolio</div>
</footer>

${allTags.length > 0 ? renderTagFilterScript() : ""}
</body>
</html>`;
  return { path: "index.html", content: html };
}
function buildEditorialPage(note, siteTitle) {
  var _a;
  const title = (_a = note.frontmatter.title) != null ? _a : note.slug;
  const date = note.frontmatter.date;
  const tags = Array.isArray(note.frontmatter.tags) ? note.frontmatter.tags : [];
  const tagHtml = tags.map((t) => `<span class="vf-page-ed-tag">${escapeHtml(String(t))}</span>`).join("");
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)} \u2014 ${escapeHtml(siteTitle)}</title>
  <style>${EDITORIAL_CSS}</style>
</head>
<body class="vf-editorial">

<a href="../index.html" class="vf-page-ed-back">&larr; Back to portfolio</a>

<header class="vf-page-ed-header">
  <div class="vf-page-ed-issue">Feature Project</div>
  <h1 class="vf-page-ed-title">${escapeHtml(title)}</h1>
  <div class="vf-page-ed-meta">${date ? escapeHtml(date) : "Recent Work"}</div>
</header>

<main class="vf-page-ed-content">
  <div class="vf-prose-ed">
    ${markdownToHtml(note.body)}
  </div>
  ${tagHtml ? `<div class="vf-page-ed-tags">${tagHtml}</div>` : ""}
</main>

</body>
</html>`;
  return { path: `pages/${note.slug}.html`, content: html };
}
var APPLE_CSS = `
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body.vf-apple {
  background: #f5f5f7;
  color: #1d1d1f;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}
.vf-apple a { color: inherit; text-decoration: none; }
.vf-apple img { max-width: 100%; height: auto; display: block; border-radius: 12px; }

/* Navigation */
.vf-nav-ap {
  position: sticky; top: 0; z-index: 100;
  background: rgba(255, 255, 255, 0.7);
  backdrop-filter: saturate(180%) blur(20px);
  -webkit-backdrop-filter: saturate(180%) blur(20px);
  border-bottom: 1px solid rgba(0,0,0,0.05);
  display: flex; justify-content: space-between; align-items: center;
  padding: 0 40px; height: 52px;
}
.vf-nav-ap-logo {
  font-weight: 600; font-size: 17px; letter-spacing: -0.01em; color: #1d1d1f;
}

/* Hero */
.vf-hero-ap {
  text-align: center; padding: 120px 40px 80px; max-width: 980px; margin: 0 auto;
}
.vf-hero-ap-title {
  font-size: clamp(48px, 8vw, 80px); font-weight: 700; letter-spacing: -0.015em; line-height: 1.05; color: #1d1d1f; margin-bottom: 24px;
}
.vf-hero-ap-subtitle {
  font-size: 24px; font-weight: 400; color: #86868b; line-height: 1.33337; letter-spacing: .009em; max-width: 680px; margin: 0 auto;
}

/* Projects */
.vf-filter-bar { display: flex; flex-wrap: wrap; gap: 8px; justify-content: center; margin-bottom: 32px; }
.vf-filter-btn { background: rgba(0,0,0,0.05); color: #1d1d1f; border: none; padding: 8px 16px; border-radius: 100px; font-size: 14px; cursor: pointer; transition: all 0.2s; font-family: inherit; font-weight: 400; }
.vf-filter-btn:hover { background: rgba(0,0,0,0.1); }
.vf-filter-btn.active { background: #1d1d1f; color: #fff; font-weight: 500; }

.vf-projects-ap {
  padding: 40px; max-width: 1200px; margin: 0 auto;
}
.vf-projects-ap-grid {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 24px;
}
.vf-card-ap {
  background: #ffffff; border-radius: 18px; padding: 40px; display: flex; flex-direction: column;
  transition: transform 0.2s cubic-bezier(0,0,0.5,1), box-shadow 0.2s cubic-bezier(0,0,0.5,1);
  box-shadow: 0 4px 24px rgba(0,0,0,0.04);
}
.vf-card-ap:hover {
  transform: scale(1.02); box-shadow: 0 12px 48px rgba(0,0,0,0.08);
}
.vf-card-ap-title {
  font-size: 28px; font-weight: 600; letter-spacing: .004em; color: #1d1d1f; margin-bottom: 12px;
}
.vf-card-ap-desc {
  font-size: 17px; font-weight: 400; color: #86868b; margin-bottom: 24px; line-height: 1.47;
}
.vf-card-ap-tags {
  display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 24px;
}
.vf-tag-ap {
  background: #f5f5f7; color: #1d1d1f; font-size: 12px; font-weight: 500; padding: 4px 12px; border-radius: 100px;
}
.vf-card-ap-link {
  margin-top: auto; color: #7C3AED; font-size: 17px; font-weight: 400;
}
.vf-card-ap-link:hover { text-decoration: underline; }

/* Quote & Footer */
.vf-quote-ap {
  text-align: center; padding: 120px 40px; max-width: 800px; margin: 0 auto;
}
.vf-quote-ap p {
  font-size: 32px; font-weight: 600; color: #1d1d1f; line-height: 1.25; letter-spacing: .004em;
}
.vf-footer-ap {
  border-top: 1px solid #d2d2d7; padding: 32px 40px; text-align: center; font-size: 12px; color: #86868b;
  max-width: 980px; margin: 0 auto;
}

/* Project Page */
.vf-page-ap-header {
  text-align: center; padding: 100px 40px 60px; max-width: 800px; margin: 0 auto;
}
.vf-page-ap-title {
  font-size: 64px; font-weight: 700; color: #1d1d1f; letter-spacing: -0.015em; line-height: 1.05; margin-bottom: 16px;
}
.vf-page-ap-meta {
  font-size: 17px; color: #86868b; font-weight: 400;
}
.vf-page-ap-content {
  background: #ffffff; padding: 80px 40px; border-radius: 32px 32px 0 0; box-shadow: 0 -4px 24px rgba(0,0,0,0.04);
}
.vf-prose-ap {
  max-width: 680px; margin: 0 auto;
}
.vf-prose-ap p {
  font-size: 19px; line-height: 1.6; color: #1d1d1f; margin-bottom: 1.5rem; font-weight: 400;
}
.vf-prose-ap h2, .vf-prose-ap h3 {
  font-weight: 600; color: #1d1d1f; letter-spacing: .004em; margin-top: 2.5rem; margin-bottom: 1rem;
}
.vf-prose-ap h2 { font-size: 32px; }
.vf-prose-ap h3 { font-size: 24px; }
.vf-prose-ap a { color: #7C3AED; text-decoration: none; }
.vf-prose-ap a:hover { text-decoration: underline; }
.vf-prose-ap pre, .vf-prose-ap code {
  background: #f5f5f7; color: #1d1d1f; border-radius: 8px; font-family: ui-monospace, Menlo, Monaco, "Cascadia Mono", "Segoe UI Mono", "Roboto Mono", "Oxygen Mono", "Ubuntu Monospace", "Source Code Pro", "Fira Mono", "Droid Sans Mono", "Courier New", monospace;
}
.vf-prose-ap pre { padding: 20px; overflow-x: auto; font-size: 14px; margin: 2rem 0; }
.vf-prose-ap code { padding: 3px 6px; font-size: 0.9em; }
.vf-gallery { display: grid; grid-template-columns: repeat(2, 1fr); gap: 24px; margin: 60px 0; }
.vf-gallery.cols-4 { grid-template-columns: repeat(4, 1fr); }
.vf-gallery img { margin: 0; border-radius: 20px; box-shadow: 0 4px 20px rgba(0,0,0,0.06); width: 100%; height: 100%; object-fit: cover; }
.vf-image-single { display: flex; justify-content: center; margin: 60px 0; }
.vf-prose-ap blockquote {
  border-left: 4px solid #d2d2d7; padding-left: 1.5rem; color: #86868b; margin: 2rem 0; font-size: 24px; font-style: italic;
}
.vf-prose-ap hr { border: none; border-top: 1px solid #d2d2d7; margin: 3rem 0; }

.vf-back-ap {
  position: absolute; top: 16px; left: 40px; color: #7C3AED; font-size: 14px; font-weight: 400; z-index: 200; display: flex; align-items: center;
}
.vf-back-ap:hover { text-decoration: underline; }
${CALLOUT_CSS}
`;
function buildAppleIndex(notes, settings) {
  const siteTitle = settings.siteName;
  const rows = notes.map((n) => {
    var _a, _b;
    const title = (_a = n.frontmatter.title) != null ? _a : n.slug;
    const desc = (_b = n.frontmatter.description) != null ? _b : "";
    const tags = Array.isArray(n.frontmatter.tags) ? n.frontmatter.tags : [];
    const tagHtml = tags.slice(0, 3).map((t) => `<span class="vf-tag-ap">${escapeHtml(String(t))}</span>`).join("");
    return `
<a href="pages/${n.slug}.html" class="vf-card-ap vf-filter-card" data-tags="${escapeHtml(tags.join(" "))}">
  <div class="vf-card-ap-title">${escapeHtml(title)}</div>
  ${desc ? `<div class="vf-card-ap-desc">${escapeHtml(desc)}</div>` : ""}
  ${tagHtml ? `<div class="vf-card-ap-tags">${tagHtml}</div>` : ""}
  <div class="vf-card-ap-link">Learn more &gt;</div>
</a>`;
  }).join("\n");
  const allTags = Array.from(new Set(notes.flatMap((n) => Array.isArray(n.frontmatter.tags) ? n.frontmatter.tags : []))).sort();
  const filterHtml = allTags.length > 0 ? `
    <div class="vf-filter-bar">
      <button class="vf-filter-btn active" data-filter="all">All</button>
      ${allTags.map((t) => `<button class="vf-filter-btn" data-filter="${escapeHtml(t)}">${escapeHtml(t)}</button>`).join("")}
    </div>
  ` : "";
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(siteTitle)}</title>
  <style>${APPLE_CSS}</style>
</head>
<body class="vf-apple">

<nav class="vf-nav-ap">
  <div class="vf-nav-ap-logo">${escapeHtml(siteTitle)}</div>
  <div style="display:flex;gap:24px;align-items:center;">
    ${settings.navLinks.split(",").map((entry) => {
    const parts = entry.trim().split(":");
    const label = parts[0].trim();
    const rawHref = parts.slice(1).join(":").trim();
    if (!label || !rawHref)
      return "";
    const fullHref = normalizeNavHref(rawHref);
    const isExternal = /^https?:\/\//.test(fullHref);
    const targetAttr = isExternal ? ` target="_blank" rel="noopener noreferrer"` : "";
    return `<a href="${escapeHtml(fullHref)}" style="color:#7C3AED; font-size:14px; font-weight:400;"${targetAttr}>${escapeHtml(label)}</a>`;
  }).filter(Boolean).join("\n    ")}
  </div>
</nav>

<header class="vf-hero-ap">
  <h1 class="vf-hero-ap-title">${escapeHtml(settings.heroTitle)}</h1>
  <p class="vf-hero-ap-subtitle">${escapeHtml(settings.heroSubtitle)}</p>
</header>

<section id="work" class="vf-projects-ap">
  ${filterHtml}
  <div class="vf-projects-ap-grid">
    ${rows}
  </div>
</section>

<section class="vf-quote-ap">
  <p>${escapeHtml(settings.quoteText)}</p>
</section>

<footer class="vf-footer-ap">
  Copyright &copy; 2026 ${escapeHtml(siteTitle)}. All rights reserved. <br/>
  Published with VaultFolio.
</footer>

${allTags.length > 0 ? renderTagFilterScript() : ""}
</body>
</html>`;
  return { path: "index.html", content: html };
}
function buildApplePage(note, siteTitle) {
  var _a;
  const title = (_a = note.frontmatter.title) != null ? _a : note.slug;
  const date = note.frontmatter.date;
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)} - ${escapeHtml(siteTitle)}</title>
  <style>${APPLE_CSS}</style>
</head>
<body class="vf-apple">

<nav class="vf-nav-ap" style="justify-content: center; position: relative;">
  <a href="../index.html" class="vf-back-ap">&lt; Back</a>
  <div class="vf-nav-ap-logo">${escapeHtml(title)}</div>
</nav>

<header class="vf-page-ap-header">
  <h1 class="vf-page-ap-title">${escapeHtml(title)}</h1>
  <p class="vf-page-ap-meta">${date ? escapeHtml(date) : "Project Showcase"}</p>
</header>

<main class="vf-page-ap-content">
  <div class="vf-prose-ap">
    ${markdownToHtml(note.body)}
  </div>
</main>

<footer class="vf-footer-ap" style="border-top: none; padding-top: 80px;">
  Copyright &copy; 2026 ${escapeHtml(siteTitle)}. All rights reserved.
</footer>

</body>
</html>`;
  return { path: `pages/${note.slug}.html`, content: html };
}
var SWISS_CSS = `
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body.vf-swiss {
  background: #ffffff;
  color: #000000;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  line-height: 1.4;
  -webkit-font-smoothing: antialiased;
}
.vf-swiss a { color: inherit; text-decoration: none; }
.vf-swiss img { max-width: 100%; height: auto; display: block; border-radius: 0; }

/* Navigation */
.vf-nav-sw {
  display: grid;
  grid-template-columns: 1fr 1fr;
  padding: 40px;
  border-bottom: 1px solid #000;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: -0.02em;
  font-size: 14px;
}
.vf-nav-sw-logo { }
.vf-nav-sw-right { text-align: right; }

/* Hero */
.vf-hero-sw {
  padding: 160px 40px;
  border-bottom: 1px solid #000;
}
.vf-hero-sw-inner {
  max-width: 1200px;
}
.vf-hero-sw-title {
  font-size: clamp(64px, 12vw, 160px);
  font-weight: 700;
  letter-spacing: -0.04em;
  line-height: 0.85;
  margin-bottom: 40px;
}
.vf-hero-sw-subtitle {
  font-size: clamp(24px, 4vw, 40px);
  font-weight: 400;
  letter-spacing: -0.02em;
  max-width: 800px;
}

/* Projects */
.vf-filter-bar { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 40px; padding: 0 40px; }
.vf-filter-btn { background: transparent; color: #000; border: none; font-weight: 700; padding: 4px 0; border-bottom: 2px solid transparent; text-transform: uppercase; letter-spacing: -0.02em; font-size: 14px; cursor: pointer; }
.vf-filter-btn:hover { color: #ff0000; border-bottom-color: #ff0000; }
.vf-filter-btn.active { border-bottom-color: #000; }

.vf-projects-sw {
  padding: 0;
}
.vf-card-sw {
  display: grid;
  grid-template-columns: 80px 1fr 200px;
  align-items: center;
  padding: 60px 40px;
  border-bottom: 1px solid #000;
  transition: background 0.2s;
  color: #000;
}
.vf-card-sw:hover {
  background: #f0f0f0;
}
.vf-card-sw-num {
  font-size: 24px;
  font-weight: 700;
  color: #ff0000;
}
.vf-card-sw-title {
  font-size: clamp(40px, 6vw, 80px);
  font-weight: 700;
  letter-spacing: -0.03em;
  line-height: 1;
}
.vf-card-sw-right {
  display: flex; flex-direction: column; align-items: flex-end; gap: 8px; text-align: right;
}
.vf-card-sw-tags {
  font-size: 12px; font-weight: 700; text-transform: uppercase;
}
.vf-card-sw-arrow {
  color: #ff0000; font-size: 24px; font-weight: 700; margin-top: 16px;
}

/* Quote & Footer */
.vf-quote-sw {
  padding: 160px 40px;
  border-bottom: 1px solid #000;
  text-align: left;
}
.vf-quote-sw p {
  font-size: clamp(32px, 5vw, 64px);
  font-weight: 700;
  letter-spacing: -0.03em;
  line-height: 1.1;
  max-width: 1000px;
}
.vf-footer-sw {
  padding: 40px;
  display: grid;
  grid-template-columns: 1fr 1fr;
  font-weight: 700;
  font-size: 14px;
  text-transform: uppercase;
}
.vf-footer-sw-right { text-align: right; color: #ff0000; }

/* Project Page */
.vf-page-sw-header {
  padding: 120px 40px;
  border-bottom: 1px solid #000;
}
.vf-page-sw-title {
  font-size: clamp(64px, 10vw, 140px);
  font-weight: 700;
  letter-spacing: -0.04em;
  line-height: 0.85;
  margin-bottom: 24px;
}
.vf-page-sw-meta {
  font-size: 24px; font-weight: 400; color: #ff0000;
}
.vf-page-sw-content {
  padding: 80px 40px; max-width: 900px;
}
.vf-prose-sw {
  font-size: 24px; line-height: 1.5; font-weight: 400; letter-spacing: -0.01em;
}
.vf-prose-sw p { margin-bottom: 2rem; }
.vf-prose-sw h2 { font-size: 48px; font-weight: 700; margin: 4rem 0 2rem; line-height: 1; letter-spacing: -0.03em; }
.vf-prose-sw h3 { font-size: 32px; font-weight: 700; margin: 3rem 0 1.5rem; line-height: 1; letter-spacing: -0.02em; }
.vf-prose-sw a { color: #ff0000; border-bottom: 2px solid #ff0000; }
.vf-prose-sw a:hover { color: #000; border-bottom-color: #000; }
.vf-prose-sw img { margin: 0; width: 100%; filter: grayscale(100%); transition: filter 0.3s; }
.vf-prose-sw img:hover { filter: grayscale(0%); }
.vf-gallery { display: grid; grid-template-columns: repeat(2, 1fr); gap: 0; border: 1px solid #000; margin: 40px 0; border-bottom: none; }
.vf-gallery.cols-4 { grid-template-columns: repeat(4, 1fr); }
.vf-gallery img { border-bottom: 1px solid #000; margin: 0; width: 100%; height: 100%; object-fit: cover; filter: grayscale(100%); transition: filter 0.3s; }
.vf-gallery img:nth-child(even) { border-left: 1px solid #000; }
.vf-gallery img:hover { filter: grayscale(0%); }
.vf-image-single { display: flex; justify-content: center; margin: 4rem 0; }
.vf-prose-sw blockquote { border-left: 8px solid #ff0000; padding-left: 2rem; margin: 3rem 0; font-size: 32px; font-weight: 700; line-height: 1.2; letter-spacing: -0.02em; }
.vf-prose-sw pre { background: #f0f0f0; padding: 2rem; font-size: 16px; margin: 2rem 0; }

.vf-back-sw {
  padding: 20px 40px; border-bottom: 1px solid #000; display: block; font-weight: 700; font-size: 14px; text-transform: uppercase;
}
.vf-back-sw:hover { background: #ff0000; color: #fff; }

@media (max-width: 768px) {
  .vf-card-sw { grid-template-columns: 1fr; gap: 16px; padding: 40px 24px; }
  .vf-card-sw-right { align-items: flex-start; text-align: left; }
  .vf-nav-sw, .vf-footer-sw { padding: 24px; }
  .vf-hero-sw, .vf-quote-sw, .vf-page-sw-header { padding: 80px 24px; }
}
${CALLOUT_CSS}
`;
function buildSwissIndex(notes, settings) {
  const siteTitle = settings.siteName;
  const rows = notes.map((n, i) => {
    var _a;
    const num = String(i + 1).padStart(2, "0");
    const title = (_a = n.frontmatter.title) != null ? _a : n.slug;
    const tags = Array.isArray(n.frontmatter.tags) ? n.frontmatter.tags : [];
    const tagsStr = tags.slice(0, 3).join(" / ");
    return `
<a href="pages/${n.slug}.html" class="vf-card-sw vf-filter-card" data-tags="${escapeHtml(tags.join(" "))}">
  <div class="vf-card-sw-num">${num}</div>
  <div class="vf-card-sw-title">${escapeHtml(title)}</div>
  <div class="vf-card-sw-right">
    ${tagsStr ? `<div class="vf-card-sw-tags">${escapeHtml(tagsStr)}</div>` : ""}
    <div class="vf-card-sw-arrow">&rarr;</div>
  </div>
</a>`;
  }).join("\n");
  const allTags = Array.from(new Set(notes.flatMap((n) => Array.isArray(n.frontmatter.tags) ? n.frontmatter.tags : []))).sort();
  const filterHtml = allTags.length > 0 ? `
    <div class="vf-filter-bar">
      <button class="vf-filter-btn active" data-filter="all" style="margin-right: 16px;">All</button>
      ${allTags.map((t) => `<button class="vf-filter-btn" data-filter="${escapeHtml(t)}">${escapeHtml(t)}</button>`).join("")}
    </div>
  ` : "";
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(siteTitle)} \u2014 Swiss</title>
  <style>${SWISS_CSS}</style>
</head>
<body class="vf-swiss">

<nav class="vf-nav-sw">
  <div class="vf-nav-sw-logo">${escapeHtml(siteTitle)}</div>
  <div class="vf-nav-sw-right">Portfolio</div>
</nav>

<header class="vf-hero-sw">
  <div class="vf-hero-sw-inner">
    <h1 class="vf-hero-sw-title">${escapeHtml(siteTitle)}</h1>
    <p class="vf-hero-sw-subtitle">${escapeHtml(settings.heroSubtitle)}</p>
  </div>
</header>

<section class="vf-projects-sw">
  ${filterHtml}
  ${rows}
</section>

<section class="vf-quote-sw">
  <p>${escapeHtml(settings.quoteText)}</p>
</section>

<footer class="vf-footer-sw">
  <div>&copy; 2026 ${escapeHtml(siteTitle)}</div>
  <div class="vf-footer-sw-right">Built with VaultFolio</div>
</footer>

${allTags.length > 0 ? renderTagFilterScript() : ""}
</body>
</html>`;
  return { path: "index.html", content: html };
}
function buildSwissPage(note, siteTitle) {
  var _a;
  const title = (_a = note.frontmatter.title) != null ? _a : note.slug;
  const date = note.frontmatter.date;
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)} - ${escapeHtml(siteTitle)}</title>
  <style>${SWISS_CSS}</style>
</head>
<body class="vf-swiss">

<a href="../index.html" class="vf-back-sw">&larr; Return to Index</a>

<header class="vf-page-sw-header">
  <h1 class="vf-page-sw-title">${escapeHtml(title)}</h1>
  <div class="vf-page-sw-meta">${date ? escapeHtml(date) : "Project"}</div>
</header>

<main class="vf-page-sw-content">
  <div class="vf-prose-sw">
    ${markdownToHtml(note.body)}
  </div>
</main>

<footer class="vf-footer-sw" style="border-top: 1px solid #000;">
  <div>${escapeHtml(title)}</div>
  <div class="vf-footer-sw-right">&copy; 2026</div>
</footer>

</body>
</html>`;
  return { path: `pages/${note.slug}.html`, content: html };
}
var SIMPLE_CSS = `
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body {
  background: #ffffff;
  color: #1a1a1a;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  font-size: 16px;
  line-height: 1.6;
}
a { color: #1a1a1a; text-decoration: none; }
img { max-width: 100%; height: auto; display: block; }

/* Nav */
.sp-nav {
  padding: 20px 40px;
  border-bottom: 1px solid #eee;
}
.sp-nav-logo { font-size: 16px; font-weight: 600; }

/* Hero */
.sp-hero {
  padding: 60px 40px 48px;
  max-width: 800px;
  margin: 0 auto;
}
.sp-hero h1 { font-size: 32px; font-weight: 700; margin-bottom: 12px; }
.sp-hero p { font-size: 16px; color: #555; }

/* Projects */
.sp-section { max-width: 800px; margin: 0 auto; padding: 0 40px 80px; }
.sp-section-heading {
  font-size: 12px; font-weight: 600; text-transform: uppercase;
  letter-spacing: 0.08em; color: #999; margin-bottom: 24px;
}
.sp-cards { display: flex; flex-direction: column; gap: 16px; }
.sp-card {
  display: block;
  border: 1px solid #eee;
  padding: 24px;
  color: #1a1a1a;
}
.sp-card-title { font-size: 18px; font-weight: 600; margin-bottom: 6px; }
.sp-card-desc { font-size: 14px; color: #555; margin-bottom: 12px; }
.sp-card-tags { display: flex; flex-wrap: wrap; gap: 6px; }
.sp-tag {
  font-size: 12px; color: #777;
  padding: 2px 8px;
  border: 1px solid #ddd;
}
.sp-empty { font-size: 15px; color: #999; padding: 24px 0; }

/* Footer */
.sp-footer {
  border-top: 1px solid #eee;
  padding: 32px 40px;
  text-align: center;
  font-size: 13px;
  color: #999;
}

/* Project page */
.sp-back {
  display: inline-block;
  padding: 24px 40px 0;
  font-size: 14px;
  color: #555;
}
.sp-page-header { max-width: 800px; margin: 0 auto; padding: 32px 40px 24px; }
.sp-page-header h1 { font-size: 28px; font-weight: 700; margin-bottom: 12px; }
.sp-page-date { font-size: 13px; color: #999; margin-bottom: 12px; }
.sp-page-tags { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 0; }
.sp-page-tag {
  font-size: 12px; color: #777;
  padding: 2px 8px;
  border: 1px solid #ddd;
}
.sp-page-content { max-width: 800px; margin: 0 auto; padding: 32px 40px 80px; }

/* Prose */
.sp-prose h1 { font-size: 26px; font-weight: 700; margin: 2rem 0 0.8rem; }
.sp-prose h2 { font-size: 22px; font-weight: 700; margin: 2rem 0 0.8rem; }
.sp-prose h3 { font-size: 18px; font-weight: 600; margin: 1.5rem 0 0.6rem; }
.sp-prose h4, .sp-prose h5, .sp-prose h6 { font-size: 16px; font-weight: 600; margin: 1.2rem 0 0.5rem; }
.sp-prose p { font-size: 16px; line-height: 1.8; color: #333; margin: 1rem 0; }
.sp-prose a { color: #1a1a1a; text-decoration: underline; }
.sp-prose strong { font-weight: 600; }
.sp-prose em { font-style: italic; }
.sp-prose ul { list-style: disc; padding-left: 1.5rem; margin: 0.8rem 0; }
.sp-prose ol { list-style: decimal; padding-left: 1.5rem; margin: 0.8rem 0; }
.sp-prose li { font-size: 16px; line-height: 1.8; color: #333; margin: 0.3rem 0; }
.sp-prose code { background: #f5f5f5; padding: 1px 5px; font-size: 0.875em; font-family: 'SF Mono', Consolas, monospace; }
.sp-prose pre { background: #f5f5f5; padding: 20px; overflow-x: auto; margin: 1.5rem 0; }
.sp-prose pre code { background: none; padding: 0; }
.sp-prose blockquote { border-left: 3px solid #ddd; padding-left: 16px; color: #666; font-style: italic; margin: 1.5rem 0; }
.sp-prose hr { border: none; border-top: 1px solid #eee; margin: 2rem 0; }
.sp-prose img { width: 100%; margin: 1.5rem 0; }

@media (max-width: 640px) {
  .sp-nav { padding: 16px 20px; }
  .sp-hero { padding: 40px 20px 32px; }
  .sp-section { padding: 0 20px 60px; }
  .sp-card { padding: 18px; }
  .sp-back { padding: 16px 20px 0; }
  .sp-page-header { padding: 20px 20px 16px; }
  .sp-page-content { padding: 20px 20px 60px; }
}
${CALLOUT_CSS}
`.trim();
function buildSimpleIndex(notes, settings) {
  const siteTitle = settings.siteName; // Extract title from settings
  const cards = notes.map((n) => {
    var _a, _b;
    const title = (_a = n.frontmatter.title) != null ? _a : n.slug;
    const desc = (_b = n.frontmatter.description) != null ? _b : "";
    const tags = Array.isArray(n.frontmatter.tags) ? n.frontmatter.tags : [];
    const tagHtml = tags.map((t) => `<span class="sp-tag">${escapeHtml(t)}</span>`).join("");
    return `<a href="pages/${n.slug}.html" class="sp-card">
  <div class="sp-card-title">${escapeHtml(title)}</div>
  ${desc ? `<div class="sp-card-desc">${escapeHtml(desc)}</div>` : ""}
  ${tags.length > 0 ? `<div class="sp-card-tags">${tagHtml}</div>` : ""}
</a>`;
  }).join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(siteTitle)}</title>
  <style>${SIMPLE_CSS}</style>
</head>
<body>

<nav class="sp-nav">
  <a href="index.html" class="sp-nav-logo">${escapeHtml(siteTitle)}</a>
</nav>

<section class="sp-hero">
  <h1>${escapeHtml(siteTitle)}</h1>
  <p>${escapeHtml(settings.heroSubtitle)}</p> 
</section>

<section class="sp-section">
  <div class="sp-section-heading">Work</div>
  ${notes.length > 0 ? `<div class="sp-cards">${cards}</div>` : `<p class="sp-empty">No published projects yet.</p>`}
</section>

<footer class="sp-footer">
  ${escapeHtml(siteTitle)} &mdash; Built with VaultFolio
</footer>

</body>
</html>`;
  return { path: "index.html", content: html };
}
function buildSimplePage(note, siteTitle) {
  var _a;
  const title = (_a = note.frontmatter.title) != null ? _a : note.slug;
  const date = note.frontmatter.date;
  const tags = Array.isArray(note.frontmatter.tags) ? note.frontmatter.tags : [];
  const tagHtml = tags.map((t) => `<span class="sp-page-tag">${escapeHtml(String(t))}</span>`).join("");
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)} \u2014 ${escapeHtml(siteTitle)}</title>
  <style>${SIMPLE_CSS}</style>
</head>
<body>

<a href="../index.html" class="sp-back">&larr; Back</a>

<div class="sp-page-header">
  <h1>${escapeHtml(title)}</h1>
  ${date ? `<div class="sp-page-date">${escapeHtml(String(date))}</div>` : ""}
  ${tags.length > 0 ? `<div class="sp-page-tags">${tagHtml}</div>` : ""}
</div>

<div class="sp-page-content">
  <div class="sp-prose">
    ${markdownToHtml(note.body)}
  </div>
</div>

<footer class="sp-footer">
  ${escapeHtml(siteTitle)} &mdash; Built with VaultFolio
</footer>

</body>
</html>`;
  return { path: `pages/${note.slug}.html`, content: html };
}

// src/deployer.ts
async function deploySite(files, config, images) {
  var _a, _b;
  if (!config.githubToken) {
    return { success: false, message: "GitHub token is required. Add it in VaultFolio settings." };
  }
  if (!config.githubRepo) {
    return { success: false, message: "GitHub repository is required (format: owner/repo)." };
  }
  const parts = config.githubRepo.split("/");
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    return {
      success: false,
      message: "Repository must be in owner/repo format (e.g. username/my-portfolio)."
    };
  }
  const [owner, repo] = parts;
  const branch = (_a = config.githubBranch) != null ? _a : "gh-pages";
  try {
    const { commitSha, treeSha } = await getOrCreateBranch(owner, repo, branch, config.githubToken);
    const existingPaths = await fetchExistingPaths(owner, repo, treeSha, config.githubToken);
    const newPathSet = /* @__PURE__ */ new Set([
      ...files.keys(),
      ...images ? images.keys() : []
    ]);
    const stalePaths = findStalePaths(existingPaths, newPathSet);
    const entries = [];
    for (const [path, content] of files) {
      const sha = await createBlob(owner, repo, content, "utf-8", config.githubToken);
      entries.push({ path, mode: "100644", type: "blob", sha });
    }
    if (images) {
      for (const [path, content] of images) {
        const sha = await createBlob(owner, repo, content, "base64", config.githubToken);
        entries.push({ path, mode: "100644", type: "blob", sha });
      }
    }
    for (const path of stalePaths) {
      entries.push({ path, mode: "100644", type: "blob", sha: null });
    }
    const newTreeSha = await createTree(owner, repo, treeSha, entries, config.githubToken);
    const timestamp = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";
    const newCommitSha = await createCommit(
      owner,
      repo,
      `VaultFolio deploy \u2014 ${timestamp}`,
      newTreeSha,
      commitSha,
      config.githubToken
    );
    await updateRef(owner, repo, branch, newCommitSha, config.githubToken);
    const url = `https://${owner}.github.io/${repo}/`;
    const total = files.size + ((_b = images == null ? void 0 : images.size) != null ? _b : 0);
    return {
      success: true,
      message: `Deployed ${total} file(s). View at ${url}`,
      url
    };
  } catch (err) {
    return {
      success: false,
      message: err instanceof Error ? err.message : String(err)
    };
  }
}
async function getOrCreateBranch(owner, repo, branch, token) {
  const refRes = await ghFetch("GET", `/repos/${owner}/${repo}/git/refs/heads/${branch}`, token);
  if (refRes.ok) {
    const ref = await refRes.json();
    const commitSha = ref.object.sha;
    const commit2 = await ghJson(
      "GET",
      `/repos/${owner}/${repo}/git/commits/${commitSha}`,
      token
    );
    return { commitSha, treeSha: commit2.tree.sha };
  }
  if (refRes.status !== 404) {
    throw await buildApiError(refRes, "checking branch");
  }
  const baseSha = await findDefaultBranchSha(owner, repo, token);
  const createRes = await ghFetch("POST", `/repos/${owner}/${repo}/git/refs`, token, {
    ref: `refs/heads/${branch}`,
    sha: baseSha
  });
  if (!createRes.ok)
    throw await buildApiError(createRes, "creating branch");
  const commit = await ghJson(
    "GET",
    `/repos/${owner}/${repo}/git/commits/${baseSha}`,
    token
  );
  return { commitSha: baseSha, treeSha: commit.tree.sha };
}
async function findDefaultBranchSha(owner, repo, token) {
  for (const name of ["main", "master"]) {
    const res = await ghFetch("GET", `/repos/${owner}/${repo}/git/refs/heads/${name}`, token);
    if (res.ok) {
      const data = await res.json();
      return data.object.sha;
    }
  }
  throw new Error(
    "Could not find main or master branch. Push an initial commit to the repo first."
  );
}
async function createBlob(owner, repo, content, encoding, token) {
  const data = await ghJson(
    "POST",
    `/repos/${owner}/${repo}/git/blobs`,
    token,
    { content, encoding }
  );
  return data.sha;
}
async function createTree(owner, repo, baseTreeSha, entries, token) {
  const data = await ghJson(
    "POST",
    `/repos/${owner}/${repo}/git/trees`,
    token,
    { base_tree: baseTreeSha, tree: entries }
  );
  return data.sha;
}
async function createCommit(owner, repo, message, treeSha, parentSha, token) {
  const data = await ghJson(
    "POST",
    `/repos/${owner}/${repo}/git/commits`,
    token,
    { message, tree: treeSha, parents: [parentSha] }
  );
  return data.sha;
}
async function updateRef(owner, repo, branch, commitSha, token) {
  const res = await ghFetch(
    "PATCH",
    `/repos/${owner}/${repo}/git/refs/heads/${branch}`,
    token,
    { sha: commitSha, force: true }
  );
  if (!res.ok)
    throw await buildApiError(res, "updating branch ref");
}
async function fetchExistingPaths(owner, repo, treeSha, token) {
  const res = await ghFetch(
    "GET",
    `/repos/${owner}/${repo}/git/trees/${treeSha}?recursive=1`,
    token
  );
  if (!res.ok)
    return [];
  const data = await res.json();
  return data.tree.filter((item) => item.type === "blob").map((item) => item.path);
}
function findStalePaths(existingPaths, newPaths) {
  return existingPaths.filter(
    (p) => (p.endsWith(".html") || p.startsWith("images/")) && !newPaths.has(p)
  );
}
function ghFetch(method, path, token, body) {
  return fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: body !== void 0 ? JSON.stringify(body) : void 0
  });
}
async function ghJson(method, path, token, body) {
  const res = await ghFetch(method, path, token, body);
  if (!res.ok)
    throw await buildApiError(res, `${method} ${path}`);
  return res.json();
}
async function buildApiError(res, context) {
  let detail = res.statusText;
  try {
    const body = await res.json();
    if (body.message)
      detail = body.message;
  } catch (e) {
  }
  if (res.status === 401) {
    return new Error("Invalid GitHub token. Check your token in VaultFolio settings.");
  }
  if (res.status === 404) {
    return new Error(
      `Not found while ${context}. Check the repository name and token permissions.`
    );
  }
  return new Error(`GitHub API error ${res.status} (${context}): ${detail}`);
}

// src/ui/settingsTab.ts
var import_obsidian = require("obsidian");
var VaultFolioSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "VaultFolio Settings" });
    containerEl.createEl("h3", { text: "Site" });
    new import_obsidian.Setting(containerEl).setName("Site name").setDesc("Displayed as your portfolio heading.").addText(
      (text) => text.setPlaceholder("My Portfolio").setValue(this.plugin.settings.siteName).onChange(async (value) => {
        this.plugin.settings.siteName = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Portfolio folder").setDesc("Folder in your vault containing notes to publish.").addText(
      (text) => text.setPlaceholder("portfolio").setValue(this.plugin.settings.portfolioFolder).onChange(async (value) => {
        this.plugin.settings.portfolioFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Output folder").setDesc("Local folder where HTML files are written.").addText(
      (text) => text.setPlaceholder("_site").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
        this.plugin.settings.outputFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Theme").setDesc("Visual style for your generated site.").addDropdown(
      (drop) => drop.addOption("default", "Dark Cinematic (Default)").addOption("editorial", "Editorial").addOption("apple", "Apple Minimalist").addOption("swiss", "Minimal Swiss").addOption("simple", "Simple").setValue(this.plugin.settings.theme).onChange(async (value) => {
        this.plugin.settings.theme = value;
        await this.plugin.saveSettings();
      })
    );
    const previewLink = containerEl.createEl("a", { text: "Preview all themes \u2192" });
    previewLink.style.cssText = "color: #7C3AED; font-size: 12px; cursor: pointer; display: inline-block; margin: -0.5rem 0 1rem 0; padding: 0 1rem; text-decoration: none;";
    previewLink.addEventListener("click", (e) => {
      e.preventDefault();
      window.open("https://thedozcompany.github.io/vaultfolio-portfolio/theme-preview.html", "_blank");
    });
    containerEl.createEl("h3", { text: "Site Content" });
    new import_obsidian.Setting(containerEl).setName("Nav Menu Links").setDesc("Format: 'Label: URL, Label: URL' (e.g. 'Work: #work, About: #about')").addTextArea(
      (text) => text.setPlaceholder("Work: #work, GitHub: https://github.com/...").setValue(this.plugin.settings.navLinks).onChange(async (value) => {
        this.plugin.settings.navLinks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Hero Title").setDesc("The main large text on the homepage.").addText(
      (text) => text.setPlaceholder("Pro. Beyond.").setValue(this.plugin.settings.heroTitle).onChange(async (value) => {
        this.plugin.settings.heroTitle = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Hero Subtitle").setDesc("The text below the main hero title.").addTextArea(
      (text) => text.setPlaceholder("Welcome to my digital portfolio.").setValue(this.plugin.settings.heroSubtitle).onChange(async (value) => {
        this.plugin.settings.heroSubtitle = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("About Text").setDesc("Text shown in the About section (HTML supported).").addTextArea(
      (text) => text.setPlaceholder("I'm a designer and developer...").setValue(this.plugin.settings.aboutText).onChange(async (value) => {
        this.plugin.settings.aboutText = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Quote Text").setDesc("Quote displayed above the footer.").addTextArea(
      (text) => text.setPlaceholder('"The details are not the details. They make the design."').setValue(this.plugin.settings.quoteText).onChange(async (value) => {
        this.plugin.settings.quoteText = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "GitHub Deploy" });
    new import_obsidian.Setting(containerEl).setName("GitHub repository").setDesc("Format: username/repository-name").addText(
      (text) => text.setPlaceholder("owner/repo").setValue(this.plugin.settings.githubRepo).onChange(async (value) => {
        this.plugin.settings.githubRepo = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("GitHub token").setDesc("Classic token with repo scope. Never shared outside your machine.").addText((text) => {
      text.setPlaceholder("ghp_...").setValue(this.plugin.settings.githubToken).onChange(async (value) => {
        this.plugin.settings.githubToken = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    const tokenWarning = containerEl.createEl("p", {
      text: "\u26A0\uFE0F Use a classic token with repo scope only. Fine-grained tokens are not supported."
    });
    tokenWarning.style.cssText = "color: #FF4D00; font-size: 0.8rem; margin: -0.5rem 0 1.5rem 0; padding: 0 1rem; line-height: 1.5;";
    const saveSeparator = containerEl.createDiv();
    saveSeparator.style.cssText = "border-top: 1px solid rgba(255,255,255,0.08); padding-top: 20px; margin-top: 20px;";
    const saveBtn = saveSeparator.createEl("button", { text: "Save Settings" });
    saveBtn.style.cssText = "background: #7C3AED; color: white; border: 1px solid #5B21B6; border-radius: 6px; padding: 10px 5px; font-size: 13px; font-weight: 500; cursor: pointer;  display: flex;  letter-spacing: 0.02em; transition: background 0.15s ease;";
    saveBtn.addEventListener("mouseenter", () => {
      saveBtn.style.background = "#5B21B6";
    });
    saveBtn.addEventListener("mouseleave", () => {
      saveBtn.style.background = "#7C3AED";
    });
    saveBtn.addEventListener("click", async () => {
      await this.plugin.saveSettings();
      new import_obsidian.Notice("\u2705 Settings saved.");
    });
  }
};

// src/ui/sidebarView.ts
var import_obsidian2 = require("obsidian");
var SIDEBAR_VIEW_TYPE = "vaultfolio-sidebar";
var VaultFolioSidebarView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.notes = [];
    this.isLoading = false;
    this.plugin = plugin;
  }
  getViewType() {
    return SIDEBAR_VIEW_TYPE;
  }
  getDisplayText() {
    return "VaultFolio";
  }
  getIcon() {
    return "layout";
  }
  async onOpen() {
    this.isLoading = true;
    this.render();
    await this.refresh(false);
  }
  async onClose() {
  }
  // ── Data ──────────────────────────────────────────────────────────────────
  async refresh(notify) {
    this.isLoading = true;
    this.notes = await this.plugin.parser.getPublishedNotes();
    this.isLoading = false;
    this.render();
    if (notify) {
      new import_obsidian2.Notice(`Refreshed. ${this.notes.length} note${this.notes.length === 1 ? "" : "s"} found.`);
    }
  }
  // ── Render ────────────────────────────────────────────────────────────────
  render() {
    const root = this.containerEl.children[1];
    root.empty();
    root.addClass("vaultfolio-sidebar");
    this.renderHeader(root);
    this.renderNoteList(root);
    this.renderFooter(root);
  }
  renderHeader(root) {
    const header = root.createDiv({ cls: "vaultfolio-header" });
    const titleEl = header.createEl("span", { cls: "vaultfolio-title" });
    titleEl.innerHTML = 'VAULT<span style="color:#FF4D00">FOLIO</span>';
    const refreshBtn = header.createEl("button", {
      cls: "vaultfolio-icon-btn",
      attr: { "aria-label": "Refresh notes" }
    });
    refreshBtn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
      fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/>
      <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/>
    </svg>`;
    refreshBtn.addEventListener("click", async () => {
      refreshBtn.addClass("vaultfolio-spinning");
      await this.refresh(true);
      refreshBtn.removeClass("vaultfolio-spinning");
    });
    if (!this.isLoading) {
      const statsRow = root.createDiv({ cls: "vaultfolio-stats-row" });
      statsRow.createSpan({
        cls: "vaultfolio-note-count-badge",
        text: `${this.notes.length} published`
      });
    }
  }
  renderNoteList(root) {
    const container = root.createDiv({ cls: "vaultfolio-note-list" });
    if (this.isLoading) {
      container.createDiv({ cls: "vaultfolio-loading", text: "Scanning vault\u2026" });
      return;
    }
    if (this.notes.length === 0) {
      const empty = container.createDiv({ cls: "vaultfolio-empty" });
      empty.createDiv({ cls: "vaultfolio-empty-icon", text: "\u{1F4DD}" });
      empty.createDiv({ cls: "vaultfolio-empty-title", text: "No published notes yet" });
      empty.createDiv({
        cls: "vaultfolio-empty-sub",
        text: "Add published: true to any note in your portfolio folder"
      });
      return;
    }
    for (const note of this.notes) {
      this.renderNoteCard(container, note);
    }
  }
  renderNoteCard(container, note) {
    const card = container.createDiv({ cls: "vaultfolio-note-card" });
    card.createDiv({ cls: "vaultfolio-note-title", text: note.title });
    const date = note.frontmatter.date;
    if (typeof date === "string" && date.trim()) {
      card.createDiv({ cls: "vaultfolio-note-date", text: date.trim() });
    }
    const tags = note.frontmatter.tags;
    if (Array.isArray(tags) && tags.length > 0) {
      const tagRow = card.createDiv({ cls: "vaultfolio-tag-row" });
      for (const tag of tags) {
        tagRow.createSpan({ cls: "vaultfolio-tag", text: String(tag).toLowerCase() });
      }
    }
  }
  renderFooter(root) {
    const footer = root.createDiv({ cls: "vaultfolio-footer" });
    const buildBtn = footer.createEl("button", {
      text: "Build Site",
      cls: ["vaultfolio-btn", "vaultfolio-btn-primary"]
    });
    const deployBtn = footer.createEl("button", {
      text: "Deploy to GitHub",
      cls: ["vaultfolio-btn", "vaultfolio-btn-secondary"]
    });
    buildBtn.addEventListener("click", async () => {
      buildBtn.disabled = true;
      deployBtn.disabled = true;
      buildBtn.setText("Building\u2026");
      try {
        const result = await this.plugin.buildSite();
        new import_obsidian2.Notice(
          `\u2705 Site built successfully \u2014 ${result.pageCount} page${result.pageCount === 1 ? "" : "s"} generated`
        );
      } catch (err) {
        new import_obsidian2.Notice(
          `\u274C Build failed \u2014 ${err instanceof Error ? err.message : "check your portfolio folder"}`
        );
      } finally {
        buildBtn.disabled = false;
        deployBtn.disabled = false;
        buildBtn.setText("Build Site");
      }
    });
    deployBtn.addEventListener("click", async () => {
      var _a;
      buildBtn.disabled = true;
      deployBtn.disabled = true;
      try {
        deployBtn.setText("Building\u2026");
        const buildResult = await this.plugin.buildSite();
        deployBtn.setText("Deploying\u2026");
        const result = await this.plugin.deployFiles(buildResult.files, buildResult.imageMap);
        if (result.success) {
          new import_obsidian2.Notice(`\u{1F680} Deployed! Visit: ${(_a = result.url) != null ? _a : result.message}`);
        } else {
          const msg = result.message;
          if (msg.includes("Invalid GitHub token") || msg.includes("401")) {
            new import_obsidian2.Notice("\u274C Invalid GitHub token \u2014 regenerate in GitHub settings");
          } else {
            new import_obsidian2.Notice("\u274C Deploy failed \u2014 check your GitHub token and repo");
          }
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        if (msg.toLowerCase().includes("fetch") || msg.toLowerCase().includes("network")) {
          new import_obsidian2.Notice("\u274C Network error \u2014 check your connection");
        } else if (msg.includes("token") || msg.includes("401")) {
          new import_obsidian2.Notice("\u274C Invalid GitHub token \u2014 regenerate in GitHub settings");
        } else {
          new import_obsidian2.Notice(`\u274C Deploy failed \u2014 ${msg}`);
        }
      } finally {
        buildBtn.disabled = false;
        deployBtn.disabled = false;
        deployBtn.setText("Deploy to GitHub");
      }
    });
  }
};

// src/main.ts
var VaultFolioPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    console.log("VaultFolio loaded");
    await this.loadSettings();
    this.parser = new Parser(this.app, this.settings);
    this.registerView(
      SIDEBAR_VIEW_TYPE,
      (leaf) => new VaultFolioSidebarView(leaf, this)
    );
    this.addRibbonIcon("layout", "VaultFolio", () => {
      new import_obsidian3.Notice("VaultFolio is ready");
      this.activateSidebar();
    });
    this.addSettingTab(new VaultFolioSettingsTab(this.app, this));
    this.addCommand({
      id: "open-sidebar",
      name: "Open VaultFolio sidebar",
      callback: () => this.activateSidebar()
    });
    this.addCommand({
      id: "build-site",
      name: "Build site",
      callback: async () => {
        try {
          const result = await this.buildSite();
          new import_obsidian3.Notice(
            `\u2705 Site built successfully \u2014 ${result.pageCount} page${result.pageCount === 1 ? "" : "s"} generated`
          );
        } catch (err) {
          new import_obsidian3.Notice(
            `\u274C Build failed \u2014 ${err instanceof Error ? err.message : "check your portfolio folder"}`
          );
        }
      }
    });
    this.addCommand({
      id: "deploy-site",
      name: "Deploy to GitHub Pages",
      callback: async () => {
        var _a;
        try {
          const result = await this.deploy();
          if (result.success) {
            new import_obsidian3.Notice(`\u{1F680} Deployed! Visit: ${(_a = result.url) != null ? _a : result.message}`);
          } else {
            const msg = result.message;
            if (msg.includes("Invalid GitHub token") || msg.includes("401")) {
              new import_obsidian3.Notice("\u274C Invalid GitHub token \u2014 regenerate in GitHub settings");
            } else {
              new import_obsidian3.Notice("\u274C Deploy failed \u2014 check your GitHub token and repo");
            }
          }
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          if (msg.toLowerCase().includes("fetch") || msg.toLowerCase().includes("network")) {
            new import_obsidian3.Notice("\u274C Network error \u2014 check your connection");
          } else {
            new import_obsidian3.Notice(`\u274C Deploy failed \u2014 ${msg}`);
          }
        }
      }
    });
    this.app.workspace.onLayoutReady(async () => {
      if (!this.settings.githubRepo) {
        new import_obsidian3.Notice("\u{1F44B} Welcome to VaultFolio! Go to Settings \u2192 VaultFolio to get started.");
      }
      const notes = await this.parser.getPublishedNotes();
      console.log("Published notes found:", notes.length);
      console.log(notes);
    });
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(SIDEBAR_VIEW_TYPE);
  }
  // ── Public methods used by UI ──────────────────────────────────────────────
  async buildSite() {
    var _a;
    const publishedNotes = await getPublishedNotes(
      this.app,
      this.settings.portfolioFolder
    );
    const siteNotes = publishedNotes.map((n) => parseNote(n.content, n.path));
    const result = buildSite(siteNotes, this.settings);
    const outputBase = this.settings.outputFolder.replace(/\/+$/, "");
    const adapter = this.app.vault.adapter;
    for (const dir of [outputBase, `${outputBase}/pages`, `${outputBase}/images`]) {
      if (!await adapter.exists(dir)) {
        await adapter.mkdir(dir);
      }
    }
    for (const file of result.files) {
      await adapter.write(`${outputBase}/${file.path}`, file.content);
    }
    const imageMap = /* @__PURE__ */ new Map();
    for (const note of publishedNotes) {
      for (const ref of note.imageRefs) {
        const vaultPath = this.resolveImageRef(ref, note.path);
        if (!vaultPath)
          continue;
        const deployPath = `images/${(_a = vaultPath.split("/").pop()) != null ? _a : vaultPath}`;
        if (imageMap.has(deployPath))
          continue;
        imageMap.set(deployPath, vaultPath);
        if (await adapter.exists(vaultPath)) {
          const binary = await adapter.readBinary(vaultPath);
          await adapter.writeBinary(`${outputBase}/${deployPath}`, binary);
        }
      }
    }
    result.imageMap = imageMap;
    return result;
  }
  async deployFiles(files, imageMap) {
    const filesMap = new Map(files.map((f) => [f.path, f.content]));
    const imageFiles = /* @__PURE__ */ new Map();
    if (imageMap) {
      for (const [deployPath, vaultPath] of imageMap) {
        try {
          const binary = await this.app.vault.adapter.readBinary(vaultPath);
          imageFiles.set(deployPath, arrayBufferToBase64(binary));
        } catch (e) {
        }
      }
    }
    return deploySite(
      filesMap,
      { githubToken: this.settings.githubToken, githubRepo: this.settings.githubRepo },
      imageFiles
    );
  }
  async deploy() {
    const buildResult = await this.buildSite();
    return this.deployFiles(buildResult.files, buildResult.imageMap);
  }
  // ── Settings ──────────────────────────────────────────────────────────────
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ── Helpers ───────────────────────────────────────────────────────────────
  resolveImageRef(ref, notePath) {
    var _a;
    if (ref.type === "wikilink") {
      const file = this.app.metadataCache.getFirstLinkpathDest(ref.path, notePath);
      return (_a = file == null ? void 0 : file.path) != null ? _a : null;
    }
    const noteDir = notePath.includes("/") ? notePath.split("/").slice(0, -1).join("/") : "";
    const clean = ref.path.replace(/^\.\//, "");
    return noteDir ? `${noteDir}/${clean}` : clean;
  }
  async activateSidebar() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(SIDEBAR_VIEW_TYPE);
    if (existing.length > 0) {
      workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({ type: SIDEBAR_VIEW_TYPE, active: true });
      workspace.revealLeaf(leaf);
    }
  }
};
function arrayBufferToBase64(buffer) {
  let binary = "";
  const bytes = new Uint8Array(buffer);
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}
